# Generated by Django 5.0.7 on 2024-08-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Desktops', 'Desktops'), ('Laptops', 'Laptops'), ('Servers', 'Servers'), ('Network', 'Network'), ('UPS', 'UPS'), ('Audio/Visual', 'Audio/Visual')], max_length=50)),
                ('asset_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
