# Generated by Django 5.0.7 on 2024-08-13 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_staff_asset_issue_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_assets',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
