# Generated by Django 5.0.7 on 2024-08-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_issue_assets_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue_assets',
            options={'verbose_name_plural': 'Issue an Asset'},
        ),
        migrations.AddField(
            model_name='asset',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue_assets',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dashboard.staff'),
        ),
    ]
