# Generated by Django 5.0.7 on 2024-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_issue_assets_options_asset_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_assets',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
