# Generated by Django 5.0.7 on 2024-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_issue_assets_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Faulty', 'Faulty'), ('Obsolete', 'Obsolete'), ('Lost', 'Lost'), ('Disposed', 'Disposed')], default=(('Working', 'Working'),), max_length=50),
            preserve_default=False,
        ),
    ]
